version: '2'
services:
  postgres:
    image: "postgres:9.6.2"
    environment:
      POSTGRES_USER: "revent"
      POSTGRES_PASSWORD: "revent_secret"
  rabbit:
    image: "rabbitmq:3.6.9-management"
    ports:
      - "5672:5672"
      - "5671:5671"
      - "25672:25672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "revent"
      RABBITMQ_DEFAULT_PASS: "revent_secret"

  web:
    build: .
    ports:
     - "4000:4000"
    volumes:
     - .:/webapps/revent_dispatcher
     - /webapps/revent_dispatcher/node_modules
    links:
      - postgres
      - rabbit
    depends_on:
      - postgres
      - rabbit
